platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking',         '~> 2.5.4'
pod 'Mantle',               '~> 2.0.2'
pod 'libextobjc',           '~> 0.4.1'
pod 'SDWebImage',           '~> 3.7.2'